### ISSUE TITLE
StreetView hangs/freeze (black space)

### ISSUE THREAD

**Issue by vitto-moz** [nesterapp/react-native-streetview#14]
Have an issue while use on Android
I should say, it doesn't occur every time I use street view in app. 
I can definitely say - issue occurs after the route changed (so maybe it related with a component instantiation) 
When street view stuck - I have next state (there is always a black line on top - it's absent when everything ok)
![image](https://user-images.githubusercontent.com/19843391/40001068-0cd11742-5796-11e8-8605-812c239ab91f.png)
every time I change route (logout/login) and use streetView - the black space grows
but if app start from a route where streetView component situated - everything ok - it works
I use "react-native-router-flux": "3.39.2" for navigation

**Comment by vitto-moz** [comment]
any comments, please... :)

**Comment by vitto-moz** [comment]
For those who stack with this issue. 
I moved to react-native-navigation, and this bug disappeared

**Comment by scotbond** [comment]
Workaround available #12

**Comment by chrise86** [comment]
@vitto-moz I’m using react-native-navigation and all I get is a black screen. Did you face this issue at all?

**Comment by vitto-moz** [comment]
@chrise86, I've ended up with my own routing and I'm totally happy with it. But my suggestion for you is - 
react-navigation
I think it's the best, comparing all available

**Comment by chrise86** [comment]
@vitto-moz I've fixed the issue and have put a pull request in, if you ever need it.

**Comment by gopisathya** [comment]
> @vitto-moz I’m using react-native-navigation and all I get is a black screen. Did you face this issue at all?

same issue for me any one got solved??
