### ISSUE TITLE
Street View gives black screen; works when ipad is connected to mac

### ISSUE THREAD

**Issue by govindj1991** [nesterapp/react-native-streetview#19]
I have been using react-native-streetview in my project and it was working all good. Until recently we noticed that it is only working when we run the app on any ipad connected to the mac from Xcode in which we develop it. If I release the ipa and test it on the same ipad, streetview returns a black screen like in[https://github.com/nesterapp/react-native-streetview/issues/3](url) . But we have the sdk key added to the app and we even have react-native-maps working correctly.

react-native @0.55.4
react-native-streetview@0.1.4

**Comment by chrise86** [comment]
@govindj1991 did you manage to resolve your issue?

**Comment by govindj1991** [comment]
@chrise86 . I couldn't with react-native-streetview. I tried upgrading to 0.1.5, which made the black screen to come even when my ipad is connected to mac :( .
I fell back to using google maps app. I simiply used Linking to open the map url pattern as follows : http://maps.google.com/maps?q=&layer=c&cbll='**lat**','**long**'
which opens up streetview in google maps native app. This again has issues when I upgraded to IOS 12 where I am intermittently getting 'cannot reach server' error in google maps app.(working fine on IOS v<12)

**Comment by chrise86** [comment]
Oh that’s disappointing 😔 that’s not an option in my case 😕

**Comment by rommel-pocomos** [comment]
Hi,

Any solutions to this? I'm having the same problem.

**Comment by wiredots01** [comment]
Hi,

Im having the same problem, any chance for work around on this?

**Comment by fullstact69** [comment]
Same problem at my side, Still no one resolved this error?

**Comment by jayeshnarola** [comment]
same problem, it only shows black screen. any solution?
