### ISSUE TITLE
Black screen on ios

### ISSUE THREAD

**Issue by voanhtuan318** [nesterapp/react-native-streetview#27]
I have a problem on ios which is only black on my screen 
<img width="350" alt="screen shot 2019-03-08 at 4 31 16 pm" src="https://user-images.githubusercontent.com/44761312/54020412-4c3b6d00-41c0-11e9-8fee-896c6a2a64a6.png">

**Comment by vitto-moz** [comment]
the same behavior, however, it worked before

**Comment by vitto-moz** [comment]
Moving google api key to the top - solved my issue 
![AppDelegate_m__Working_Tree__—_MinifinderGo](https://user-images.githubusercontent.com/19843391/56082703-926d9700-5e24-11e9-85fe-7a815850e210.png)
