### ISSUE TITLE
Callback mismatch between iOS and Android

### ISSUE THREAD

**Issue by taknuti** [nesterapp/react-native-streetview#28]
We use the 'onError' callback to render a map if, for whatever reason, street view is not loading. This week we discovered this was not working on Android. After diving a bit in the repo I found that on Android the callback is called 'onStreetViewError'.

This is a bit confusing and not well documented. I would suggest making the names the same. If not, a bit of documentation to explain this might be welcome.

**Comment by scotbond** [comment]
Fixed by #36
