### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by n23daniel** [nesterapp/react-native-streetview#3]
I followed all steps on setting the google maps sdk. I get no errors, but I only see a spinner for ~1 second followed by a black screen with the google logo on the bottom left side regardless of what latitude and longitude I set. The area prevents me from scrolling so something is happening there, but the images are somehow not loaded.

**Comment by n23daniel** [comment]
Silly me...  I had to enable the Google Maps SDK for iOS from the Google Console.

**Comment by chrise86** [comment]
I have this issue even though I have enabled the Maps SDK for iOS. Has anyone else had this issue?

**Comment by thomashermine** [comment]
@chrise86 Great! I used your fork, it works perfectly !

**Comment by fullstact69** [comment]
onError={(event) => console.log('failed to load map', event.nativeEvent)}
Always it is called. How to fix this?
