### ISSUE TITLE
How to get the updated latitude and longitude when moving, is there any subscribe event?

### ISSUE THREAD

**Issue by roysG** [nesterapp/react-native-streetview#32]
Let׳s say i start in some position (lat,long) and start moving on the street,
How can i get the updated location (lat,long)?

**Comment by Windastella** [comment]
Any updates on this?

**Comment by MichaelTaylor3D** [comment]
Im interested in this as well.

**Comment by MichaelTaylor3D** [comment]
It seems that this was working in IOS but wasnt finished in Android. I made a pull request to make this work in android. https://github.com/nesterapp/react-native-streetview/pull/36

**Comment by scotbond** [comment]
PR Merged. Thanks @MichaelTaylor3D !
