### ISSUE TITLE
React/RCTViewManager.h not found

### ISSUE THREAD

**Issue by mikemcelligott** [nesterapp/react-native-streetview#34]
This seems to have something to do with header file discovery, but when I attempt to compile after adding (and linking) react-native-streetview I get a compilation error on the NSTStreetView project.  Specifically it can't find React/RCTViewManager.h.  When I check the header search paths it looks like node_modules/react-native/React is listed (non-recursive), but as of RN 0.61 at least the files are now in subdirectories (React/Views/RCTViewManager.h in this case).  If I change the header search path and make it recursive (as well as update to just "RCTViewManager.h" instead of <React/RCTViewManager.h> in the import) other bugs start to pop up.

I'm not sure if something has changed in 0.61 or if this problem has been longstanding but I'm not good enough at xcode build settings to figure it out so far.

<img width="676" alt="Screen Shot 2019-10-16 at 12 33 24 PM" src="https://user-images.githubusercontent.com/487946/66939561-44bf2a80-f011-11e9-91cb-79fc31e3ccf1.png">

**Comment by scotbond** [comment]
This issue was caused by injecting NSStreetView as a static library rather than a Pod.
Adding podspec at  #1fa3327 fixes that.
Please upgrade with npm to version 0.2.1.
