### ISSUE TITLE
requireNativeComponent NSTView not found in the UIModule

### ISSUE THREAD

**Issue by gattaloukik123** [nesterapp/react-native-streetview#37]
Can anyone please help me out with this problem, i am running the application on an android device and I have got no iOS or android simulators installed. How do I overcome this error?

**Comment by jalapenos8** [comment]
Did you find answer?

**Comment by amitpdev** [comment]
react-native-streetview v0.2.4 is now released. auto-linking should work as well. I tested with latest RN 0.72.2 (see updated example as well)
Please upgrade and report your issue status. thanks!
