### ISSUE TITLE
requireNativeComponent: "NSTStreetView" was not found in the UIManager.

### ISSUE THREAD

**Issue by bhishakBitcanny** [nesterapp/react-native-streetview#41]
StreetView crashing in iOS. use_framework! is enabled in pods.

"react-native-streetview": "0.2.1"
"react": "16.13.1",
"react-native": "0.63.2"

![IMG_2C2915187DD1-1](https://user-images.githubusercontent.com/49839906/99648474-182ddb80-2a79-11eb-9fb2-f3bee16219cf.jpeg)

**Comment by kbits-Mars** [comment]
Did you find any solution for this error?

**Comment by bhishakBitcanny** [comment]
@kbits-Mars nothing yet

**Comment by shivanibc662** [comment]
after installing  react-native-streetview : 
1. npx react-native link react-native-streetview
2.  cd ios 
3.  pod install
4. run

**Comment by bhishakBitcanny** [comment]
@shivanibc662 can you please let me know your RN version?

**Comment by shivanibc662** [comment]
0.64.0
But I think it should work on 63 also.

**Comment by bhishakBitcanny** [comment]
@shivanibc662 Then if you already have autolinking then why "npx react-native link react-native-streetview"?

**Comment by shivanibc662** [comment]
Some react native package need to link manually. after react native
updation this happens sometimes.

**Comment by amitpdev** [comment]
react-native-streetview  v0.2.4 is now released. auto-linking should work as well. I tested with latest RN 0.72.2 (see updated example as well)
Please upgrade and report your issue status. thanks!
