### ISSUE TITLE
Invariant Violation: requireNativeComponent: "NSTStreetView" was not found in the UIManager.

### ISSUE THREAD

**Issue by kbits-Mars** [nesterapp/react-native-streetview#42]
"react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-streetview": "~0.2.1"
emulator: Android Studio

I try to use the react-native-street view component in an android emulator and I get the following error, anyone who knows any solution for this error?
![component exception](https://user-images.githubusercontent.com/74271079/100670539-04ae2a80-332d-11eb-8616-5f50ba6f62e7.png)

**Comment by shivanibc662** [comment]
after installing react-native-streetview :

1. npx react-native link react-native-streetview
2. cd ios
3. pod install
4. run

**Comment by fudr** [comment]
> "react": "16.13.1", "react-native": "0.63.4", "react-native-streetview": "~0.2.1" emulator: Android Studio
> 
> I try to use the react-native-street view component in an android emulator and I get the following error, anyone who knows any solution for this error? ![component exception](https://user-images.githubusercontent.com/74271079/100670539-04ae2a80-332d-11eb-8616-5f50ba6f62e7.png)

Hi did you get anything?

**Comment by amitpdev** [comment]
v0.2.4 is now released. please remove current version and install with:

```sh
yarn install react-native-streetview@0.2.4
cd ios
pod install
cd ..
npx react-native run-ios
```
