### ISSUE TITLE
In order to compile Java 9+ source, please set compileSdkVersion to 30 or above

### ISSUE THREAD

**Issue by ShaziaNasim606** [nesterapp/react-native-streetview#49]
While compileSdkVersion is 33 and i tried all options available but still i am facing this issue.
In order to compile Java 9+ source, please set compileSdkVersion to 30 or above

**Comment by amitpdev** [comment]
Im on it. new version will be released soon

**Comment by ShaziaNasim606** [comment]
I solved this issue by making these changes in node_modules/react-native-streetview/build.gradle
minSdkVersion safeExtGet('minSdkVersion', 21)
targetSdkVersion safeExtGet('targetSdkVersion', 33)

**Comment by amitpdev** [comment]
@ShaziaNasim606 you may use v0.2.2 released today
