### ISSUE TITLE
No variants found for ':react-native-streetview'. Check build files to ensure at least one variant exists

### ISSUE THREAD

**Issue by williamswebworks** [nesterapp/react-native-streetview#50]
Suddenly getting the error message No variants found for ':react-native-streetview'. Check build files to ensure at least one variant exists when trying to sync gradle in android. Unsure why it is happening now as it was working fine in recent builds.

Any help is appreciated

**Comment by Winter2141** [comment]
System:
    OS: macOS 14.0
    CPU: (12) x64 Intel(R)
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.0/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    Watchman: 2023.09.25.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.13.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10811636
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.8 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.71.13 => 0.71.13 
    react-native-streetview =>  "^0.2.2"

I had the same issue.

**Comment by williamswebworks** [comment]
How did you fix it?

**Comment by amitpdev** [comment]
v0.2.4 is now released, please upgrade and report. Thanks!
