### ISSUE TITLE
iOS configuration not compatible with teams or CI

### ISSUE THREAD

**Issue by grahamyesfit** [nesterapp/react-native-streetview#7]
There's a manual step for iOS to put the search path to the Google API in the NSTStreetView project. This change will only affect my local development environment and team members will have to do the same when they pull this library from NPM. And it won't even work for CI (I'm using buddy build) because it's always a fresh pull from NPM. Is there a solution for this? Is there a setting in my global workspace where I can specify the path?

**Comment by scotbond** [comment]
This manual step was removed in 13f84f1359dc01a4fd4aa204dcc0fe3f7b878667.
Installing GoogleMaps using CocoaPods is now supported by Google and is the recommended way for react-native-streetview to work out of the box. Your CI tools should have no issues now. Thanks for reporting this.
