### ISSUE TITLE
Compiler error in building stage

### ISSUE THREAD

**Issue by tyw1012** [nesterapp/react-native-streetview#9]
I got following error message after I hit  react-native run-android.

C:\Users\YW\Desktop\myapp\node_modules\react-native-streetview\android\src\main\java\co\il\nester\android\react\streetview\NSTStreetViewPackage.java:27: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
Incremental compilation of 1 classes completed in 0.488 secs.
:react-native-streetview:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-streetview:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

What should I do? My react native version is 50.3
Thank you.

**Comment by TolgaCagin** [comment]
Remove or comment @override line from related file

**Comment by tyw1012** [comment]
@TolgaCagin Thanks. it works now.

 After I commented it out, I had to change the js>StreetView.js file as here to avoid this message: 'undefined is not an object (evaluating '_react 3.default.proptypes.shape')' 
` import PropTypes from 'prop-types';
....
coordinate: PropTypes.shape({
		latitude: PropTypes.number.isRequired,
		longitude: PropTypes.number.isRequired,`
